design_styles = {
    "realistic_image": "Realistic photography of humans, objects, or environments, with natural lighting and lifelike details.",
    "realistic_image/b_and_w": "Black and white realistic photography with high contrast and detailed textures.",
    "realistic_image/hard_flash": "Realistic photography with intense, direct flash lighting for dramatic effect.",
    "realistic_image/hdr": "High dynamic range realistic photography with vibrant colors and enhanced details.",
    "realistic_image/natural_light": "Realistic photography using soft, natural lighting for a serene look.",
    "realistic_image/studio_portrait": "Realistic studio portrait photography with controlled lighting and clean backgrounds.",
    "realistic_image/enterprise": "Professional, corporate-style realistic photography with polished and modern aesthetics.",
    "realistic_image/motion_blur": "Realistic photography with subtle motion blur to convey movement.",
    "realistic_image/evening_light": "Realistic photography with warm, golden-hour lighting for a cozy ambiance.",
    "realistic_image/faded_nostalgia": "Realistic photography with a faded, vintage look for nostalgic appeal.",
    "realistic_image/forest_life": "Realistic photography capturing natural forest environments with organic textures.",
    "realistic_image/mystic_naturalism": "Realistic photography with a mystical, ethereal quality in natural settings.",
    "realistic_image/natural_tones": "Realistic photography with earthy, muted color palettes.",
    "realistic_image/organic_calm": "Realistic photography with calming, organic tones and soft lighting.",
    "realistic_image/real_life_glow": "Realistic photography with a vibrant, glowing effect for lifelike vibrancy.",
    "realistic_image/retro_realism": "Realistic photography with a retro aesthetic, mimicking older photographic styles.",
    "realistic_image/retro_snapshot": "Realistic photography styled like a vintage snapshot with soft edges and warm tones.",
    "realistic_image/urban_drama": "Realistic photography with dramatic urban settings and bold lighting.",
    "realistic_image/village_realism": "Realistic photography capturing rustic village life with authentic details.",
    "realistic_image/warm_folk": "Realistic photography with warm, folk-inspired tones and cozy aesthetics.",
    "digital_illustration": "Hand-drawn or digitally created illustrations, with stylized artwork and vibrant colors.",
    "digital_illustration/pixel_art": "Digital illustration in a pixelated, retro video game style.",
    "digital_illustration/hand_drawn": "Digital illustration mimicking hand-drawn sketches with organic lines.",
    "digital_illustration/grain": "Digital illustration with a grainy texture for a vintage feel.",
    "digital_illustration/infantile_sketch": "Digital illustration with a playful, childlike sketch style.",
    "digital_illustration/2d_art_poster": "Digital illustration styled like bold, flat 2D art posters.",
    "digital_illustration/handmade_3d": "Digital illustration with a handmade, pseudo-3D effect.",
    "digital_illustration/hand_drawn_outline": "Digital illustration with hand-drawn outlines and minimal color.",
    "digital_illustration/engraving_color": "Digital illustration mimicking colored engravings with fine details.",
    "digital_illustration/2d_art_poster_2": "Digital illustration with a vibrant, modern 2D poster aesthetic.",
    "digital_illustration/antiquarian": "Digital illustration with an antique, historical art style.",
    "digital_illustration/bold_fantasy": "Digital illustration with bold, fantastical elements and vibrant colors.",
    "digital_illustration/child_book": "Digital illustration styled for children's books with soft, whimsical details.",
    "digital_illustration/child_books": "Digital illustration for children's books with playful, colorful designs.",
    "digital_illustration/cover": "Digital illustration designed for book or magazine covers with striking visuals.",
    "digital_illustration/crosshatch": "Digital illustration using crosshatching techniques for texture.",
    "digital_illustration/digital_engraving": "Digital illustration mimicking detailed engravings with sharp lines.",
    "digital_illustration/expressionism": "Digital illustration with expressive, abstract, and emotional styles.",
    "digital_illustration/freehand_details": "Digital illustration with freehand, detailed linework.",
    "digital_illustration/grain_20": "Digital illustration with a subtle grain texture for added depth.",
    "digital_illustration/graphic_intensity": "Digital illustration with intense, high-contrast graphic elements.",
    "digital_illustration/hard_comics": "Digital illustration in a bold, comic-book style with strong outlines.",
    "digital_illustration/long_shadow": "Digital illustration with long, dramatic shadows for a modern look.",
    "digital_illustration/modern_folk": "Digital illustration with a contemporary folk art aesthetic.",
    "digital_illustration/multicolor": "Digital illustration with vibrant, multicolor palettes.",
    "digital_illustration/neon_calm": "Digital illustration with neon colors and a calm, modern vibe.",
    "digital_illustration/noir": "Digital illustration with a dark, noir-inspired aesthetic.",
    "digital_illustration/nostalgic_pastel": "Digital illustration with soft, nostalgic pastel tones.",
    "digital_illustration/outline_details": "Digital illustration with detailed outlines and minimal shading.",
    "digital_illustration/pastel_gradient": "Digital illustration with smooth pastel gradients.",
    "digital_illustration/pastel_sketch": "Digital illustration mimicking soft pastel sketches.",
    "digital_illustration/pop_art": "Digital illustration in a bold, pop-art style with bright colors.",
    "digital_illustration/pop_renaissance": "Digital illustration blending pop art with renaissance aesthetics.",
    "digital_illustration/street_art": "Digital illustration inspired by urban street art and graffiti.",
    "digital_illustration/tablet_sketch": "Digital illustration mimicking sketches drawn on a tablet.",
    "digital_illustration/urban_glow": "Digital illustration with a glowing, urban-inspired aesthetic.",
    "digital_illustration/urban_sketching": "Digital illustration mimicking urban sketchbook art.",
    "digital_illustration/vanilla_dreams": "Digital illustration with soft, dreamy vanilla tones.",
    "digital_illustration/young_adult_book": "Digital illustration styled for young adult book covers.",
    "digital_illustration/young_adult_book_2": "Digital illustration for young adult books with a modern twist.",
    "vector_illustration": "Flat, graphic vector art, often with clean lines and solid colors, typically used in logos and modern designs.",
    "vector_illustration/bold_stroke": "Vector illustration with bold, thick strokes and minimalistic design.",
    "vector_illustration/chemistry": "Vector illustration with a scientific, chemistry-inspired aesthetic.",
    "vector_illustration/colored_stencil": "Vector illustration mimicking colored stencil art.",
    "vector_illustration/contour_pop_art": "Vector illustration with contour lines and pop-art influences.",
    "vector_illustration/cosmics": "Vector illustration with cosmic, space-inspired themes.",
    "vector_illustration/cutout": "Vector illustration with a paper-cutout aesthetic.",
    "vector_illustration/depressive": "Vector illustration with a moody, depressive tone.",
    "vector_illustration/editorial": "Vector illustration styled for editorial and publishing purposes.",
    "vector_illustration/emotional_flat": "Vector illustration with flat design and emotional undertones.",
    "vector_illustration/infographical": "Vector illustration designed for infographics with clear visuals.",
    "vector_illustration/marker_outline": "Vector illustration with marker-style outlines.",
    "vector_illustration/mosaic": "Vector illustration with a mosaic, tiled aesthetic.",
    "vector_illustration/naivector": "Vector illustration with a naive, simplistic art style.",
    "vector_illustration/roundish_flat": "Vector illustration with rounded, flat shapes.",
    "vector_illustration/segmented_colors": "Vector illustration with segmented, distinct color blocks.",
    "vector_illustration/sharp_contrast": "Vector illustration with high-contrast, sharp visuals.",
    "vector_illustration/thin": "Vector illustration with thin, delicate lines.",
    "vector_illustration/vector_photo": "Vector illustration mimicking a realistic photo style.",
    "vector_illustration/vivid_shapes": "Vector illustration with vivid, bold shapes.",
    "vector_illustration/engraving": "Vector illustration mimicking traditional engravings.",
    "vector_illustration/line_art": "Vector illustration with clean, minimal line art.",
    "vector_illustration/line_circuit": "Vector illustration with circuit-like line patterns.",
    "vector_illustration/linocut": "Vector illustration mimicking linocut printmaking."
}